### ISSUE TITLE
Hi, can you send me the source Files?

### ISSUE THREAD

**Issue by andiling** [mgrl/0816-feeder-mechanics#1]
Hallo, habe auf der Webseite gelesen ich könnte auf Anfrage an die Quelldaten der Feeder kommen. Ich würde mit daraus sehr gerne einen intelligenten Feeder entwickeln! Die Mechanik gefällt mir sehr gut!

Gruß

Andi

**Comment by mgineer85** [comment]
---

**Comment by andiling** [comment]
Herzlichen Dank!

**Comment by volter50000** [comment]
Hi. I really liked the mechanics. I tried making it on my 3d printer and it works great. I would like to reconfigure the feeders to fit my machine. Could you share the source files of this feeder. Thank you very much for the work you have done.
